GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzMyMzQ0NDI1LCJleHAiOjE3MzIzNDQ0NDB9.TMNmyLSlROVNXhu6wsOOPFGxM0INMAUlqTPBFTg24yw


###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzMyMzQ1MjA2fQ.3jxHrR5JuRPIH1jPBKyF738uW3x_Kx94l5VUAl9sZck"
}


###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzMyMzQ1MjA2fQ.3jxHrR5JuRPIH1jPBKyF738uW3x_Kx94l5VUAl9sZck"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jim"
}